//! Scaffold a starter knowledge base from the bundled seed.
//!
//! Only the slices and conventions relevant to the project's stacks are copied — an
//! Android project should not start life owning Rust conventions it will never read.

use std::collections::BTreeSet;
use std::path::Path;

use anyhow::{bail, Result};
use include_dir::{include_dir, Dir};

use crate::kb::schema::Slice;

static SEED: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/seed");

const FACTS_README: &str = "Generated by `repo-task index` — do not edit by hand.

Each file is one fact family declared in kb.yaml. Commit them so agents share the
same view of the project, and refresh them whenever the code moves.
";

fn read(path: &str) -> Result<&'static str> {
    SEED.get_file(path)
        .and_then(|file| file.contents_utf8())
        .ok_or_else(|| anyhow::anyhow!("Bundled seed is missing {path}"))
}

fn names(directory: &str, suffix: &str) -> Vec<String> {
    let Some(dir) = SEED.get_dir(directory) else {
        return Vec::new();
    };
    let mut found: Vec<String> = dir
        .files()
        .filter_map(|file| {
            let name = file.path().file_name()?.to_string_lossy().to_string();
            name.strip_suffix(suffix).map(|stem| stem.to_string())
        })
        .collect();
    found.sort();
    found
}

/// The stacks' slices plus everything they extend.
fn selected_slices(stacks: &[String]) -> Result<Vec<String>> {
    let available: BTreeSet<String> = names("slices", ".yaml").into_iter().collect();
    let mut selected: BTreeSet<String> = BTreeSet::new();
    let mut pending: Vec<String> = stacks
        .iter()
        .filter(|stack| available.contains(*stack))
        .cloned()
        .collect();
    if pending.is_empty() {
        pending.push("generic".to_string());
    }
    while let Some(current) = pending.pop() {
        if selected.contains(&current) || !available.contains(&current) {
            continue;
        }
        selected.insert(current.clone());
        let slice: Slice = serde_norway::from_str(read(&format!("slices/{current}.yaml"))?)?;
        pending.extend(slice.extends);
    }
    Ok(selected.into_iter().collect())
}

pub fn scaffold(target: &Path, stacks: &[String], force: bool) -> Result<Vec<String>> {
    if target.join("kb.yaml").exists() && !force {
        bail!(
            "{} already exists. Pass --force to overwrite the seed files.",
            target.join("kb.yaml").display()
        );
    }

    let slice_names = selected_slices(stacks)?;
    let mut conventions: BTreeSet<String> = BTreeSet::new();
    let mut recipes: BTreeSet<String> = BTreeSet::new();
    for name in &slice_names {
        let slice: Slice = serde_norway::from_str(read(&format!("slices/{name}.yaml"))?)?;
        conventions.extend(slice.conventions);
        recipes.extend(slice.recipes);
    }

    let mut convention_files: Vec<String> = names("conventions", ".md")
        .into_iter()
        .filter(|name| conventions.contains(&format!("{name}-conventions")))
        .collect();
    if convention_files.is_empty() {
        convention_files = vec!["common".into(), "generic".into()];
    }

    let mut written: Vec<String> = Vec::new();
    let mut copy = |relative: String, content: &str| -> Result<()> {
        let path = target.join(&relative);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, content)?;
        written.push(relative);
        Ok(())
    };

    copy("kb.yaml".into(), read("kb.yaml")?)?;
    for name in &convention_files {
        copy(
            format!("conventions/{name}.md"),
            read(&format!("conventions/{name}.md"))?,
        )?;
    }
    for name in &recipes {
        copy(
            format!("recipes/{name}.md"),
            read(&format!("recipes/{name}.md"))?,
        )?;
    }
    for name in &slice_names {
        copy(
            format!("slices/{name}.yaml"),
            read(&format!("slices/{name}.yaml"))?,
        )?;
    }
    copy("facts/README.md".into(), FACTS_README)?;
    Ok(written)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_dir(label: &str) -> std::path::PathBuf {
        std::env::temp_dir().join(format!(
            "repotask-seed-{label}-{}-{:?}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ))
    }

    #[test]
    fn copies_only_the_relevant_stacks() {
        let target = temp_dir("stacks");

        scaffold(&target, &["android".into(), "kotlin".into()], false).unwrap();

        assert!(target.join("conventions/android.md").is_file());
        assert!(!target.join("conventions/ios.md").exists());
        assert!(!target.join("conventions/rust.md").exists());
        std::fs::remove_dir_all(&target).ok();
    }

    #[test]
    fn follows_slice_inheritance() {
        let target = temp_dir("inherit");

        scaffold(&target, &["jetpack-compose".into()], false).unwrap();

        let slices: BTreeSet<String> = std::fs::read_dir(target.join("slices"))
            .unwrap()
            .flatten()
            .map(|entry| {
                entry
                    .path()
                    .file_stem()
                    .unwrap()
                    .to_string_lossy()
                    .to_string()
            })
            .collect();
        assert_eq!(
            slices,
            ["android", "generic", "jetpack-compose"]
                .into_iter()
                .map(String::from)
                .collect::<BTreeSet<_>>()
        );
        std::fs::remove_dir_all(&target).ok();
    }

    #[test]
    fn falls_back_to_generic_for_unknown_stacks() {
        let target = temp_dir("unknown");

        scaffold(&target, &["cobol".into()], false).unwrap();

        assert!(target.join("slices/generic.yaml").is_file());
        std::fs::remove_dir_all(&target).ok();
    }

    #[test]
    fn references_only_recipes_it_copied() {
        let target = temp_dir("recipes");

        scaffold(&target, &["android".into()], false).unwrap();

        let copied: BTreeSet<String> = std::fs::read_dir(target.join("recipes"))
            .unwrap()
            .flatten()
            .map(|entry| {
                entry
                    .path()
                    .file_stem()
                    .unwrap()
                    .to_string_lossy()
                    .to_string()
            })
            .collect();
        for entry in std::fs::read_dir(target.join("slices")).unwrap().flatten() {
            let slice: Slice =
                serde_norway::from_str(&std::fs::read_to_string(entry.path()).unwrap()).unwrap();
            for recipe in slice.recipes {
                assert!(
                    copied.contains(&recipe),
                    "slice references uncopied recipe {recipe}"
                );
            }
        }
        std::fs::remove_dir_all(&target).ok();
    }

    #[test]
    fn refuses_to_clobber_without_force() {
        let target = temp_dir("clobber");
        scaffold(&target, &["android".into()], false).unwrap();

        assert!(scaffold(&target, &["android".into()], false).is_err());
        assert!(scaffold(&target, &["android".into()], true).is_ok());
        std::fs::remove_dir_all(&target).ok();
    }
}
