"""Scaffold a starter knowledge base from the bundled seed.

Only the slices and conventions relevant to the project's stacks are copied — an
Android project should not start life owning Rust conventions it will never read.
"""

from __future__ import annotations

from importlib import resources
from importlib.resources.abc import Traversable
from pathlib import Path

import yaml

from repotask.errors import RepoTaskError
from repotask.files import write_text

SEED_PACKAGE = "repotask.seed"
FACTS_README = """Generated by `repo-task index` — do not edit by hand.

Each file is one fact family declared in kb.yaml. Commit them so agents share the
same view of the project, and refresh them whenever the code moves.
"""


def _seed_root() -> Traversable:
    return resources.files(SEED_PACKAGE)


def _read(*parts: str) -> str:
    node = _seed_root()
    for part in parts:
        node = node.joinpath(part)
    return node.read_text(encoding="utf-8")


def _names(directory: str, suffix: str) -> list[str]:
    node = _seed_root().joinpath(directory)
    return sorted(
        item.name.removesuffix(suffix)
        for item in node.iterdir()
        if item.name.endswith(suffix) and not item.name.startswith("_")
    )


def _selected_slices(stacks: list[str]) -> list[str]:
    """The stacks' slices plus everything they extend."""
    available = set(_names("slices", ".yaml"))
    selected: set[str] = set()
    pending = [stack for stack in stacks if stack in available]
    if not pending:
        pending = ["generic"]
    while pending:
        current = pending.pop()
        if current in selected or current not in available:
            continue
        selected.add(current)
        document = yaml.safe_load(_read("slices", f"{current}.yaml")) or {}
        pending.extend(document.get("extends", []))
    return sorted(selected)


def scaffold(target: Path, stacks: list[str], force: bool = False) -> list[str]:
    if target.exists() and any(target.iterdir()) and not force:
        existing = target / "kb.yaml"
        if existing.exists():
            raise RepoTaskError(
                f"{existing} already exists. Pass --force to overwrite the seed files."
            )

    slice_names = _selected_slices(stacks)
    conventions: set[str] = set()
    recipes: set[str] = set()
    for name in slice_names:
        document = yaml.safe_load(_read("slices", f"{name}.yaml")) or {}
        conventions.update(document.get("conventions", []))
        recipes.update(document.get("recipes", []))

    convention_files = {
        name: f"{name}.md"
        for name in _names("conventions", ".md")
        if f"{name}-conventions" in conventions
    }
    if not convention_files:
        convention_files = {"common": "common.md", "generic": "generic.md"}

    written: list[str] = []

    def copy(relative: str, content: str) -> None:
        write_text(target / relative, content)
        written.append(relative)

    copy("kb.yaml", _read("kb.yaml"))
    for filename in sorted(convention_files.values()):
        copy(f"conventions/{filename}", _read("conventions", filename))
    for name in sorted(recipes):
        copy(f"recipes/{name}.md", _read("recipes", f"{name}.md"))
    for name in slice_names:
        copy(f"slices/{name}.yaml", _read("slices", f"{name}.yaml"))
    copy("facts/README.md", FACTS_README)
    return written
